#!/bin/bash

# Load variables
source "${PROJECT_DIR}/config.sh"
# Variables:
# CONTAINER_NAME
# CONTAINER_BACKUP_NAME
# CONTAINER_FOLDER_USER
# CONTAINER_FOLDER_BACKUP_USER
# BACKUP_FILE_CONTAINER
# BACKUP_FILE_DATA

#Container
rm -rf "${CONTAINER_FOLDER_BACKUP_USER}"
mkdir "${CONTAINER_FOLDER_BACKUP_USER}"
mkdir "${BACKUP_FILE_DATA}"
cp -r "${CONTAINER_FOLDER_USER}" "${BACKUP_FILE_DATA}"
docker commit "${CONTAINER_NAME}" "${CONTAINER_BACKUP_NAME}"
docker export -o "${BACKUP_FILE_CONTAINER}" "${CONTAINER_NAME}"
docker image rm "${CONTAINER_BACKUP_NAME}"
